version: '3'

services:
  pg:
    image: postgres
    container_name: dbpostgres
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=godriver
    ports:
      - 5432:5432
    volumes:
      - .pgdata:/var/lib/postgresql/data
    networks:
      - godriver

  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: godriver_rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    networks:
      - godriver

networks:
  godriver:
    driver: bridge
